<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit83eadf4f297c9725d8a828cd89fe1c71
{
    public static $prefixesPsr0 = array (
        'P' => 
        array (
            'Phroute' => 
            array (
                0 => __DIR__ . '/..' . '/phroute/phroute/src',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInit83eadf4f297c9725d8a828cd89fe1c71::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
